[package]
name = "build_deno"
version = "0.1.0"
edition = "2021"

[dependencies]
deno = "=1.36.2"
deno_runtime = { version = "0.124.0" }
tokio = { version = "1.26.0", features = ["full"] }
log = "0.4"
simple-logging = "2.0.2"
async-ffi = {version = "0.5.0", features = ["macros"]}
jni = "0.21.1"
futures = "0.3"
url = { version = "2.3.1", features = ["serde", "expose_internals"] }
# fix for cargo metadata
v8 = "0.75.1"

[lib]
path = "src/main.rs"
crate-type = ["dylib"]

[patch.crates-io]
v8 = { path = "./workdir/v8-0.75.1" }
deno_runtime = { path = "./workdir/deno_runtime-0.124.0" }
deno_fs = { path = "./workdir/deno_fs-0.26.0" }
deno_node = { path = "./workdir/deno_node-0.53.0" }
libsqlite3-sys = { path= "./workdir/libsqlite3-sys-0.26.0" }